### ISSUE TITLE
where package BertConfig and BertModel

### ISSUE THREAD

**Issue by geekbeing** [frankaging/Quasi-Attention-ABSA#1]
when i excute the file "convert_tf_checkpoint_to_pytorch.py"  
i got the error:  ModuleNotFoundError: No module named 'model.BERT'
where can i get  the module "model.BERT" or package BertConfig and BertModel ?
thx

**Comment by frankaging** [comment]
Hi, thanks for your comments.

There are two ways to solve this issue:
(1) Switch to using pytorch model file if you are looking for official BERT releases.

(2) I have added the missing module just now **model.BERT**, so the convert script shall work. We stopped updating it because we switch to pytorch model file later on. Please pull main, and retry.
