### ISSUE TITLE
Can't train CG-BERT model

### ISSUE THREAD

**Issue by guardiaum** [frankaging/Quasi-Attention-ABSA#3]
Hi, I am unable to train the CG-BERT model for any dataset. Below is the running command I've used and the result log. I have changed just the training batch size and evaluation interval. This error occurs for any dataset when setting the model type to CGBERT. I have successfully trained the QACGBERT model.

````
$ CUDA_VISIBLE_DEVICES=0 python run_classifier.py --task_name semeval_NLI_M 
--data_dir ../datasets/semeval2014/ 
--output_dir ../results/semeval2014/CGBERT-reproduce/ 
--model_type CGBERT 
--do_lower_case --max_seq_length 128 
--train_batch_size 32 --eval_batch_size 256
--learning_rate 2e-5 --num_train_epochs 30 
--vocab_file uncased_L-12_H-768_A-12/vocab.txt 
--bert_config_file uncased_L-12_H-768_A-12/bert_config.json 
--init_checkpoint uncased_L-12_H-768_A-12/pytorch_model.bin 
--seed 123 --evaluate_interval 500 --context_standalone

05/17/2021 12:53:53 - INFO - util.train_helper -   device cuda n_gpu 1 distributed training False
output_log_file= ../results/semeval2014/CGBERT-reproduce/log.txt
05/17/2021 12:53:53 - INFO - util.train_helper -   *** Model Config ***
05/17/2021 12:53:53 - INFO - util.train_helper -   {
  "attention_probs_dropout_prob": 0.1,
  "full_pooler": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

05/17/2021 12:53:53 - INFO - util.train_helper -   model = CGBERT
init_weight = True
05/17/2021 12:53:54 - INFO - util.train_helper -   retraining with saved model.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 15220/15220 [00:02<00:00, 5133.30it/s]
05/17/2021 12:53:58 - INFO - util.train_helper -   ***** Running training *****
05/17/2021 12:53:58 - INFO - util.train_helper -     Num examples = 15220
05/17/2021 12:53:58 - INFO - util.train_helper -     Batch size = 32
05/17/2021 12:53:58 - INFO - util.train_helper -     Num steps = 14268
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:00<00:00, 4770.35it/s]
Iteration:   0%|                                                                                                 | 0/476 [00:00<?, ?it/s]
Epoch:   0%|                                                                                                      | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_classifier.py", line 39, in <module>
    run(args)
  File "run_classifier.py", line 30, in run
    output_log_file, epoch, global_best_acc, args)
  File "~/Quasi-Attention-ABSA/code/util/train_helper.py", line 729, in step_train
    context_ids=context_ids)
ValueError: not enough values to unpack (expected 6, got 2)
```

**Comment by frankaging** [comment]
Hi, Thanks for your inputs.

Yes, this is a TODO before. I was manually changing some lines of codes. This is due to the fact that CGBERT returns 2 data structs whereas QACGBERT returns more than 2 (the others were for analyses purposes), and we forgot to change CGBERT.

The fix just checked in. It is a one line change, you can refer to it and pull the master. Or you can simply change the line by yourself.

I attached logs from my manual testing:

06/04/2021 15:51:23 - INFO - util.train_helper -   model = CGBERT
init_weight = True
06/04/2021 15:51:25 - INFO - util.train_helper -   retraining with saved model.
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 15220/15220 [00:03<00:00, 4500.98it/s]
06/04/2021 15:51:30 - INFO - util.train_helper -   ***** Running training *****
06/04/2021 15:51:30 - INFO - util.train_helper -     Num examples = 15220
06/04/2021 15:51:30 - INFO - util.train_helper -     Batch size = 32
06/04/2021 15:51:30 - INFO - util.train_helper -     Num steps = 14268
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:00<00:00, 4346.86it/s]
Epoch:   0%|                                                                                                       | 0/30 [00:00<?, ?it/s/dfs/user/wuzhengx/workspace/Quasi-Attention-ABSA/code/util/optimization.py:146: UserWarning: This overload of add_ is deprecated:?, ?it/s]
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:1005.)
  next_m.mul_(beta1).add_(1 - beta1, grad)

Iteration:   8%|█████▋                                                                  | 38/476

Happy debugging! Thanks!

**Comment by guardiaum** [comment]
Hi, @frankaging thanks for your feedback. I have just run the command for training CGBERT and all went well. Thanks
